services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    ports:
      - "32400:32400"       # Web UI
      - "32469:32469"       # GDM network discovery
      - "8324:8324"         # Remote control
      - "1900:1900/udp"     # DLNA discovery
      - "32410:32410/udp"   # GDM network discovery
      - "32412:32412/udp"   # GDM network discovery
      - "32413:32413/udp"   # GDM network discovery
      - "32414:32414/udp"   # GDM network discovery
    environment:
      - PUID=501               # Your macOS user ID
      - PGID=20                # Your macOS "staff" group ID
      - VERSION=docker
      - PLEX_CLAIM=${PLEX_CLAIM}  # Get token from https://www.plex.tv/claim/ (valid 4 min)
    volumes:
      - plex_config:/config
      - /Users/monty/Downloads/Movies:/movies
      - /Users/monty/Downloads/TV:/tv
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G

volumes:
  plex_config:
